# Generated by Django 4.2.2 on 2023-06-23 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.CreateModel(
            name='speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Bio', models.TextField(blank=True)),
                ('contact_info', models.FloatField()),
                ('Profile_picture', models.ImageField(blank=True, null=True, upload_to='speaker_images')),
                ('area_of_experience', models.CharField(max_length=255)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='speakers.category')),
            ],
        ),
    ]
