# Generated by Django 4.2.2 on 2023-06-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speakers', '0002_alter_category_options_speaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speaker',
            name='contact_info',
            field=models.CharField(max_length=50),
        ),
    ]
