# Generated by Django 4.2.2 on 2023-06-23 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_category_conference_date_conference_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
